package com.routemind.report;

import com.routemind.metrics.model.Models.MetricWithContext;
import com.routemind.persona.PersonaRouter.PersonaBundle;
import com.routemind.rules.Finding;
import org.springframework.stereotype.Service;

/**
 * The "forward to leadership without rework" artefact. Self-contained HTML —
 * no placeholders, no raw ids, every number carrying its reference point.
 */
@Service
public class ReportComposer {

    public String html(PersonaBundle b) {
        StringBuilder h = new StringBuilder();
        h.append("""
                <!doctype html><html><head><meta charset="utf-8">
                <title>Mobility briefing</title>
                <style>
                 body{font:15px/1.55 -apple-system,Segoe UI,Roboto,sans-serif;color:#1c2233;
                      max-width:860px;margin:32px auto;padding:0 20px}
                 h1{font-size:24px;margin:0 0 4px} .sub{color:#5b6478;margin-bottom:26px}
                 .card{border:1px solid #e2e6ef;border-radius:10px;padding:16px 18px;margin:12px 0}
                 .sev{display:inline-block;font-size:11px;font-weight:700;letter-spacing:.06em;
                      padding:3px 9px;border-radius:99px;color:#fff}
                 .HIGH{background:#c0392b}.MEDIUM{background:#d98324}.LOW{background:#7a869a}
                 .k{color:#5b6478;font-size:13px}
                 table{border-collapse:collapse;width:100%;margin-top:8px;font-size:13px}
                 td,th{border-bottom:1px solid #eef0f5;text-align:left;padding:7px 6px}
                 .val{font-weight:600}
                </style></head><body>
                """);

        h.append("<h1>").append(esc(b.displayName())).append(" — mobility briefing</h1>");
        h.append("<div class='sub'>").append(b.from()).append(" to ").append(b.to());
        if (b.businessUnit() != null) h.append(" · ").append(esc(b.businessUnit()));
        h.append(" · ").append(esc(b.need())).append("</div>");

        if (b.findings().isEmpty()) {
            h.append("<div class='card'>No issues crossed the alerting thresholds "
                    + "for this period. All tracked metrics are within target.</div>");
        }

        for (Finding f : b.findings()) {
            h.append("<div class='card'>");
            h.append("<span class='sev ").append(f.severity()).append("'>")
             .append(f.severity()).append("</span> &nbsp;<strong>")
             .append(esc(f.displayName())).append("</strong>");
            h.append("<p>").append(esc(f.narrative())).append("</p>");
            h.append("<div class='k'>value <span class='val'>").append(f.value())
             .append("</span> · target <span class='val'>").append(f.target()).append("</span>");
            if (f.priorValue() != null)
                h.append(" · previous <span class='val'>").append(f.priorValue()).append("</span>");
            h.append("</div>");
            if (f.attribution() != null && !f.attribution().isEmpty()) {
                h.append("<table><tr><th>").append(esc(f.attributionDimension()))
                 .append("</th><th>share</th></tr>");
                f.attribution().forEach(c -> h.append("<tr><td>").append(esc(c.member()))
                        .append("</td><td>").append(c.pct()).append("%</td></tr>"));
                h.append("</table>");
            }
            h.append("</div>");
        }

        h.append("<h3>All tracked metrics</h3><table>")
         .append("<tr><th>Metric</th><th>Value</th><th>Target</th><th>Previous</th><th>Status</th></tr>");
        for (MetricWithContext m : b.metrics()) {
            h.append("<tr><td>").append(esc(m.displayName())).append("</td><td class='val'>")
             .append(m.value()).append("</td><td>").append(m.target()).append("</td><td>")
             .append(m.priorValue() == null ? "—" : m.priorValue()).append("</td><td>")
             .append(m.status()).append("</td></tr>");
        }
        h.append("</table>");
        h.append("<p class='k' style='margin-top:24px'>Generated by RouteMind. "
                + "Every figure is computed from the trip dataset; narrative wording is "
                + "generated but contains no invented numbers.</p>");
        h.append("</body></html>");
        return h.toString();
    }

    private static String esc(String s) {
        return s == null ? "" : s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
